<upgrade>
	<user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>marketplace</module_id>
			<type>integer</type>
			<admin>6</admin>
			<user>6</user>
			<guest>6</guest>
			<staff>6</staff>
			<module>marketplace</module>
			<ordering>0</ordering>
			<value>total_photo_upload_limit</value>
		</setting>
	</user_group_settings>
</upgrade>