<upgrade>
	<phpfox_update_user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>photo</module_id>
			<type>array</type>
			<admin><![CDATA[s:22:"array('20','40','60');";]]></admin>
			<user><![CDATA[s:22:"array('20','40','60');";]]></user>
			<guest><![CDATA[s:22:"array('20','40','60');";]]></guest>
			<staff><![CDATA[s:22:"array('20','40','60');";]]></staff>
			<module>photo</module>
			<ordering>0</ordering>
			<value>total_photos_displays</value>
		</setting>
	</phpfox_update_user_group_settings>
</upgrade>