<upgrade>
	<user_group_settings>
		<setting>
			<is_admin_setting>0</is_admin_setting>
			<module_id>pages</module_id>
			<type>boolean</type>
			<admin>1</admin>
			<user>1</user>
			<guest>1</guest>
			<staff>1</staff>
			<module>pages</module>
			<ordering>0</ordering>
			<value>can_view_browse_pages</value>
		</setting>
	</user_group_settings>
</upgrade>