<upgrade>
	<settings>
		<setting>
			<group>cache</group>
			<module_id>event</module_id>
			<is_hidden>0</is_hidden>
			<type>boolean</type>
			<var_name>cache_events_per_user</var_name>
			<phrase_var_name>setting_cache_events_per_user</phrase_var_name>
			<ordering>1</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>0</value>
		</setting>
		<setting>
			<group>cache</group>
			<module_id>event</module_id>
			<is_hidden>0</is_hidden>
			<type>integer</type>
			<var_name>cache_upcoming_events_info</var_name>
			<phrase_var_name>setting_cache_upcoming_events_info</phrase_var_name>
			<ordering>2</ordering>
			<version_id>3.6.0rc1</version_id>
			<value>8</value>
		</setting>
	</settings>
</upgrade>