<upgrade>
    <settings>
        <setting>
            <group></group>
            <module_id>forum</module_id>
            <is_hidden>0</is_hidden>
            <type>integer</type>
            <var_name>total_recent_posts_display</var_name>
            <phrase_var_name>setting_total_recent_posts_display</phrase_var_name>
            <ordering>5</ordering>
            <version_id>4.3.0</version_id>
            <value>20</value>
        </setting>
        <setting>
            <group></group>
            <module_id>forum</module_id>
            <is_hidden>0</is_hidden>
            <type>integer</type>
            <var_name>total_recent_discussions_display</var_name>
            <phrase_var_name>setting_total_recent_discussions_display</phrase_var_name>
            <ordering>4</ordering>
            <version_id>4.3.0</version_id>
            <value>20</value>
        </setting>
        <setting>
            <group></group>
            <module_id>forum</module_id>
            <is_hidden>0</is_hidden>
            <type>boolean</type>
            <var_name>enable_thanks_on_posts</var_name>
            <phrase_var_name>setting_enable_thanks_on_posts</phrase_var_name>
            <ordering>6</ordering>
            <version_id>4.3.0</version_id>
            <value>0</value>
        </setting>
    </settings>
</upgrade>